'use client';

import type {Metadata} from 'next/metadata';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {Toaster} from '@/components/ui/toaster';
// import { initializeFirebase } from '@/lib/firebase'; - Removed Firebase
import { useEffect, useState } from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [isInitialized, setIsInitialized] = useState(false); - Removed Firebase

  // useEffect(() => { - Removed Firebase
  //   if (!isInitialized) {
  //     initializeFirebase();
  //     setIsInitialized(true);
  //   }
  // }, [isInitialized]);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
          <Toaster />
      </body>
    </html>
  );
}
