export type SiteConfig = {
	name: string
	description: string
	url: string
	ogImage: string
	links: {
		twitter: string
		github: string
	}
}

export const siteConfig: SiteConfig = {
	name: "ConvoSpan.ai", // Updated site name
	description:
		"Generated by Firebase Studio",
	url: "https://convospan.ai",
	ogImage: "https://ui.shadcn.com/og.jpg",
	links: {
		twitter: "https://twitter.com/shadcn",
		github: "https://github.com/shadcn/ui",
	},
}