
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main # Change this to your primary branch if not main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ensure this Node.js version is compatible with your project
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci # Use npm ci for clean install in CI environments

      - name: Verify Key Secrets Availability (Test Step)
        env:
          TEST_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          TEST_GOOGLE_GENAI_API_KEY: ${{ secrets.GOOGLE_GENAI_API_KEY }}
          TEST_LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          TEST_FIREBASE_SA_KEY_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON }}
        run: |
          echo "Verifying critical environment variable availability..."
          if [ -z "$TEST_FIREBASE_PROJECT_ID" ]; then echo "ERROR: NEXT_PUBLIC_FIREBASE_PROJECT_ID is NOT SET or is empty." >&2; exit 1; else echo "SUCCESS: NEXT_PUBLIC_FIREBASE_PROJECT_ID is set."; fi
          if [ -z "$TEST_GOOGLE_GENAI_API_KEY" ]; then echo "ERROR: GOOGLE_GENAI_API_KEY is NOT SET or is empty." >&2; exit 1; else echo "SUCCESS: GOOGLE_GENAI_API_KEY is set."; fi
          if [ -z "$TEST_LINKEDIN_CLIENT_SECRET" ]; then echo "ERROR: LINKEDIN_CLIENT_SECRET is NOT SET or is empty." >&2; exit 1; else echo "SUCCESS: LINKEDIN_CLIENT_SECRET is set."; fi
          if [ -z "$TEST_FIREBASE_SA_KEY_JSON" ]; then echo "ERROR: FIREBASE_SERVICE_ACCOUNT_KEY_JSON is NOT SET or is empty." >&2; exit 1; else echo "SUCCESS: FIREBASE_SERVICE_ACCOUNT_KEY_JSON is set (length: ${#TEST_FIREBASE_SA_KEY_JSON})."; fi
          echo "Secrets availability check passed."

      - name: Build Next.js Application
        env:
          # Map environment variables from GitHub Secrets
          GOOGLE_GENAI_API_KEY: ${{ secrets.GOOGLE_GENAI_API_KEY }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          SARVAM_API_KEY: ${{ secrets.SARVAM_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # This was in your list, ensure it's a secret if used
          NEXT_PUBLIC_LINKEDIN_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          NEXT_PUBLIC_LINKEDIN_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_LINKEDIN_REDIRECT_URI }}
          SENDPULSE_CLIENT_ID: ${{ secrets.SENDPULSE_CLIENT_ID }}
          SENDPULSE_CLIENT_SECRET: ${{ secrets.SENDPULSE_CLIENT_SECRET }}
          DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
          DEFAULT_FROM_NAME: ${{ secrets.DEFAULT_FROM_NAME }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          SENDPULSE_API_BASE_URL: ${{ secrets.SENDPULSE_API_BASE_URL }}
          FIREBASE_SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON }} # For server-side admin tasks during build if any
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON }} # Use service account key for authentication
          projectId: outreachai-7bkh0 # Your Firebase Project ID
          channelId: live # Deploy to live channel by default
        env:
             FIREBASE_CLI_PREVIEWS: hostingchannels
