name: Firebase Deployment

on:
  push:
    branches:
      - main # Consider changing to 'master' if that's your primary branch
  pull_request:
    branches:
      - main # Consider changing to 'master' if that's your primary branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm' # Optional: Cache npm dependencies

      - name: Install dependencies
        run: npm ci # Changed to npm ci for more reliable builds

      - name: Build
        env:
          # Ensure all NEXT_PUBLIC_ environment variables needed by 'npm run build' are defined as secrets
          # and passed here.
          # Example:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          GOOGLE_GENAI_API_KEY: ${{ secrets.GOOGLE_GENAI_API_KEY }} # If Genkit needs it at build time
          # Add other NEXT_PUBLIC_ variables your build process requires
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_OUTREACHAI_7BKH0 }}' # Ensure this secret contains the JSON key
          channelId: live
          projectId: outreachai-7bkh0
        env: # This env block is for the deploy step, not the build step.
             # It's usually not needed for Firebase Hosting deployments unless the action itself requires specific env vars.
             FIREBASE_CLI_PREVIEWS: hostingchannels # Example if needed for specific CLI features during deploy
